In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('Recommend.csv', names=['userID', 'movieID', 'rating','timestamp'])
df.head()

userID  movieID  rating  timestamp
0     196      242       3  881250949
1     186      302       3  891717742
2      22      377       1  878887116
3     244       51       2  880606923
4     166      346       1  886397596

In [11]:
no_users = df.userID.unique().shape[0]
no_movies = df.movieID.unique().shape[0]
print(no_users)
print(no_movies)

943
1682


In [12]:
from sklearn.model_selection import train_test_split
train_data, test_data = train_test_split(df, test_size=0.25)

In [14]:
print(train_data.shape)
print(test_data.shape)

(75000, 4)
(25000, 4)


In [17]:
#creating a zero matrix for train_data using  no_users times no of movies

train_data_matrix = np.zeros((no_users, no_movies))
train_data_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [18]:
train_data_matrix.shape

(943, 1682)

In [44]:
#fill this matrix using the train data
for row in train_data.itertuples():
    #print(row)
    train_data_matrix[row[1]-1, row[2]-1] = row[3]
train_data_matrix

array([[5., 3., 4., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

In [46]:

test_data_matrix = np.zeros((no_users, no_movies))
test_data_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [47]:
#fill this matrix using the test data
for row in test_data.itertuples():
    #print(row)
    test_data_matrix[row[1]-1, row[2]-1] = row[3]
test_data_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [49]:
from sklearn.metrics.pairwise import pairwise_distances
movie_similarity = pairwise_distances(train_data_matrix.T, metric='cosine')

In [50]:
movie_similarity

array([[0.        , 0.69398691, 0.7487335 , ..., 1.        , 1.        ,
        0.94447657],
       [0.69398691, 0.        , 0.81965342, ..., 1.        , 1.        ,
        1.        ],
       [0.7487335 , 0.81965342, 0.        , ..., 1.        , 1.        ,
        1.        ],
       ...,
       [1.        , 1.        , 1.        , ..., 0.        , 1.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 0.        ,
        1.        ],
       [0.94447657, 1.        , 1.        , ..., 1.        , 1.        ,
        0.        ]])

In [51]:
movie_pred = train_data_matrix.dot(movie_similarity)/np.array([np.abs(movie_similarity).sum(axis=1)])
movie_pred

array([[0.35505354, 0.37042376, 0.38255716, ..., 0.42858335, 0.42593694,
        0.41569118],
       [0.08893746, 0.09892048, 0.09625895, ..., 0.10025585, 0.10172516,
        0.10242627],
       [0.05748851, 0.06037567, 0.05929884, ..., 0.05818667, 0.06067817,
        0.06130133],
       ...,
       [0.02308336, 0.03059476, 0.02978435, ..., 0.03466264, 0.03450327,
        0.03411241],
       [0.1316544 , 0.14063037, 0.14842389, ..., 0.15576386, 0.15585961,
        0.15572375],
       [0.20610514, 0.1994955 , 0.22680153, ..., 0.2575124 , 0.25520523,
        0.24946308]])